(function($){
	// Settings
	var repeat = localStorage.repeat || 0,
		shuffle = localStorage.shuffle || 'false',
		continous = true,
		autoplay = true,
		playlist = [
{title: '枫叶岛屿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/枫叶岛屿.mp3',ogg: ''},
{title: '冒险者讲习所',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/冒险者讲习所.mp3',ogg: ''},
{title: '游戏商城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/游戏商城.mp3',ogg: ''},	
{title: '射手村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/射手村.mp3',ogg: ''},
{title: '魔法密林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/魔法密林.mp3',ogg: ''},
{title: '废弃都市',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/废弃都市.mp3',ogg: ''},
{title: '勇士部落',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/勇士部落.mp3',ogg: ''},
{title: '诺特勒斯号内部',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/诺特勒斯号内部.mp3',ogg: ''},
{title: '诺特勒斯号港湾',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/诺特勒斯号港湾.mp3',ogg: ''},
{title: '林中之城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/林中之城.mp3',ogg: ''},
{title: '圣地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/圣地.mp3',ogg: ''},
{title: '天空之城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/天空之城.mp3',ogg: ''},
{title: '玩具城-塔外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城-塔外.mp3',ogg: ''},
{title: '玩具城-帕普拉图斯',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城-帕普拉图斯.mp3',ogg: ''},
{title: '玩具城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城.mp3',ogg: ''},
{title: '冰封雪域',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/冰封雪域.mp3',ogg: ''},
{title: '水下世界',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水下世界.mp3',ogg: ''},
{title: '阿里安特',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/阿里安特.mp3',ogg: ''},
{title: '尼哈沙漠',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/尼哈沙漠.mp3',ogg: ''},
{title: '玛加提亚',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玛加提亚.mp3',ogg: ''},
{title: '神木村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神木村.mp3',ogg: ''},

{title: '时间神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间神殿.mp3',ogg: ''},

{title: '冰之神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/冰之神殿.mp3',ogg: ''},
{title: '火之神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/火之神殿.mp3',ogg: ''},
{title: '毒之神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/毒之神殿.mp3',ogg: ''},
{title: '神的黄昏',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神的黄昏.mp3',ogg: ''},
{title: '想念你',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/想念你.mp3',ogg: ''},
{title: '扎昆',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/扎昆.mp3',ogg: ''},
{title: '扎昆的祭台',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/扎昆的祭台.mp3',ogg: ''},





{title: '尼哈黄昏沙漠',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/尼哈黄昏沙漠.mp3',ogg: ''},

{title: '玩具城工厂',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城工厂.mp3',ogg: ''},
{title: '玩具城扭曲时间(前段)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城扭曲时间(前段).mp3',ogg: ''},
{title: '玩具城扭曲时间(后段)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城扭曲时间(后段).mp3',ogg: ''},
{title: '玩具塔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具塔.mp3',ogg: ''},
{title: '玩具塔塔外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具塔塔外.mp3',ogg: ''},
{title: '玩具工厂',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具工厂.mp3',ogg: ''},
{title: '玩具船与神木船',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具船与神木船.mp3',ogg: ''},
{title: '圣地修炼场',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/圣地修炼场.mp3',ogg: ''},
{title: '圣地西边',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/圣地西边.mp3',ogg: ''},
{title: '圣诞村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/圣诞村.mp3',ogg: ''},
{title: '地球防御本部',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/地球防御本部.mp3',ogg: ''},
{title: '地铁',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/地铁.mp3',ogg: ''},
{title: '坐船通往天空之城路上',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/坐船通往天空之城路上.mp3',ogg: ''},
{title: '台湾不夜城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/台湾不夜城.mp3',ogg: ''},
{title: '匠人村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/匠人村.mp3',ogg: ''},

{title: '魔法密林-树洞',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/魔法密林-树洞.mp3',ogg: ''},
{title: '魔法密林怪物地带',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/魔法密林怪物地带.mp3',ogg: ''},
{title: '魔法密林训练场',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/魔法密林训练场.mp3',ogg: ''},
{title: '射手村东部',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/射手村东部.mp3',ogg: ''},
{title: '射手村市集',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/射手村市集.mp3',ogg: ''},
{title: '射手村西部',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/射手村西部.mp3',ogg: ''},
{title: '射手村训练场',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/射手村训练场.mp3',ogg: ''},	
{title: '11周年节日现场',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/11周年节日现场.mp3',ogg: ''},
{title: '2021年平凡的村庄',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/2021年平凡的村庄.mp3',ogg: ''},
{title: '2503年天空战舰',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/2503年天空战舰.mp3',ogg: ''},

{title: '库尔兰草原',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/库尔兰草原.mp3',ogg: ''},
{title: '枫城外部',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/枫城外部.mp3',ogg: ''},
{title: 'Subway',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Subway.mp3',ogg: ''},
{title: 'Temple-of-Time-(Launty-Remix)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Temple-of-Time-(Launty-Remix).mp3',ogg: ''},
{title: 'Temple-of-Time-(Wisp-X-Remix)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Temple-of-Time-(Wisp-X-Remix).mp3',ogg: ''},
{title: 'The-Devil-Is-Coming',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/The-Devil-Is-Coming.mp3',ogg: ''},
{title: 'TheDollMaster',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/TheDollMaster.mp3',ogg: ''},
{title: 'TheLivingMountain',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/TheLivingMountain.mp3',ogg: ''},
{title: 'Through-The-Blizzard',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Through-The-Blizzard.mp3',ogg: ''},
{title: 'Time-Is-Gold',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Time-Is-Gold.mp3',ogg: ''},
{title: 'Timeless-Beholder',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Timeless-Beholder.mp3',ogg: ''},
{title: 'Title-2010-Winter',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Title-2010-Winter.mp3',ogg: ''},
{title: 'Tower-Of-Goddess',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Tower-Of-Goddess.mp3',ogg: ''},
{title: 'Travelers',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Travelers.mp3',ogg: ''},
{title: 'UndergroundPlace',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/UndergroundPlace.mp3',ogg: ''},
{title: 'UponTheSky',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/UponTheSky.mp3',ogg: ''},
{title: 'warfare-far',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/warfare-far.mp3',ogg: ''},
{title: 'Warm-Regard',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Warm-Regard.mp3',ogg: ''},
{title: 'WaterWay',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/WaterWay.mp3',ogg: ''},
{title: 'Welcome-To-The-Hell',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Welcome-To-The-Hell.mp3',ogg: ''},
{title: 'When-The-Morning-Comes',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/When-The-Morning-Comes.mp3',ogg: ''},
{title: 'Where-The-Barlog-From',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Where-The-Barlog-From.mp3',ogg: ''},
{title: 'White-Christmas',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/White-Christmas.mp3',ogg: ''},
{title: 'Wind-And-Flower',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Wind-And-Flower.mp3',ogg: ''},
{title: 'Wolf-Wood',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Wolf-Wood.mp3',ogg: ''},
{title: 'WzLogo',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/WzLogo.mp3',ogg: ''},
{title: 'なないろの世界',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/なないろの世界.mp3',ogg: ''},
{title: 'ディヴィニティ',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/ディヴィニティ.mp3',ogg: ''},
{title: '万圣赛跑',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/万圣赛跑.mp3',ogg: ''},
{title: '万神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/万神殿.mp3',ogg: ''},
{title: '万神殿圣殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/万神殿圣殿.mp3',ogg: ''},
{title: '万神殿郊外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/万神殿郊外.mp3',ogg: ''},
{title: '上海外滩',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/上海外滩.mp3',ogg: ''},
{title: '中国服-嵩山镇',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/中国服-嵩山镇.mp3',ogg: ''},
{title: '中国服-藏经阁',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/中国服-藏经阁.mp3',ogg: ''},
{title: '中国服-豫园',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/中国服-豫园.mp3',ogg: ''},
{title: '乌山上',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/乌山上.mp3',ogg: ''},
{title: '乌鲁城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/乌鲁城.mp3',ogg: ''},
{title: '修炼森林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/修炼森林.mp3',ogg: ''},
{title: '克里塞村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/克里塞村.mp3',ogg: ''},
{title: '克里塞村郊外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/克里塞村郊外.mp3',ogg: ''},
{title: '克里蒂亚斯',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/克里蒂亚斯.mp3',ogg: ''},
{title: '克里蒂亚斯市场',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/克里蒂亚斯市场.mp3',ogg: ''},

{title: '军营',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/军营.mp3',ogg: ''},


{title: '冰封雪域怪物地带',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/冰封雪域怪物地带.mp3',ogg: ''},
{title: '冰峰雪域',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/冰峰雪域.mp3',ogg: ''},
{title: '前往阿里山巅峰的路',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/前往阿里山巅峰的路.mp3',ogg: ''},

{title: '半人马的领土',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/半人马的领土.mp3',ogg: ''},

{title: '吉隆坡',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/吉隆坡.mp3',ogg: ''},
{title: '国际服结婚胜地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/国际服结婚胜地.mp3',ogg: ''},

{title: '埃德尔斯坦-EdelsteinCityInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/埃德尔斯坦-EdelsteinCityInMirror.mp3',ogg: ''},
{title: '埃德尔斯坦',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/埃德尔斯坦.mp3',ogg: ''},
{title: '埃德尔斯坦地下',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/埃德尔斯坦地下.mp3',ogg: ''},
{title: '天皇',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/天皇.mp3',ogg: ''},
{title: '天空之城-玩具城-港口',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/天空之城-玩具城-港口.mp3',ogg: ''},

{title: '天空之城船上遇boss',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/天空之城船上遇boss.mp3',ogg: ''},
{title: '女神塔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/女神塔.mp3',ogg: ''},
{title: '始まりのstory',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/始まりのstory.mp3',ogg: ''},
{title: '威尔-RedRoom',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/威尔-RedRoom.mp3',ogg: ''},
{title: '射手村-FloralLifeInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/射手村-FloralLifeInMirror.mp3',ogg: ''},

{title: '尖耳狐狸村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/尖耳狐狸村.mp3',ogg: ''},
{title: '尤娜剧情',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/尤娜剧情.mp3',ogg: ''},

{title: '希利尼提',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/希利尼提.mp3',ogg: ''},
{title: '帕普拉图斯',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/帕普拉图斯.mp3',ogg: ''},
{title: '库尔兰草原',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/库尔兰草原.mp3',ogg: ''},
{title: '废弃的塔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/废弃的塔.mp3',ogg: ''},
{title: '废弃的塔组队任务',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/废弃的塔组队任务.mp3',ogg: ''},
{title: '废矿区',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/废矿区.mp3',ogg: ''},
{title: '庭园',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/庭园.mp3',ogg: ''},
{title: '影子村-ShadowKnight',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/影子村-ShadowKnight.mp3',ogg: ''},
{title: '影子神殿-ShadowTemple',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/影子神殿-ShadowTemple.mp3',ogg: ''},
{title: '往返天空与密林的船',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/往返天空与密林的船.mp3',ogg: ''},
{title: '御龙魔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/御龙魔.mp3',ogg: ''},
{title: '怪异的回廊',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/怪异的回廊.mp3',ogg: ''},

{title: '扎昆祭台',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/扎昆祭台.mp3',ogg: ''},
{title: '扭曲的时间前段',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/扭曲的时间前段.mp3',ogg: ''},
{title: '扭曲的时间后段',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/扭曲的时间后段.mp3',ogg: ''},
{title: '新叶城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/新叶城.mp3',ogg: ''},
{title: '新叶城郊外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/新叶城郊外.mp3',ogg: ''},
{title: '时间之路',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间之路.mp3',ogg: ''},
{title: '时间异常之地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间异常之地.mp3',ogg: ''},
{title: '时间消失之路',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间消失之路.mp3',ogg: ''},
{title: '时间消失之路前段',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间消失之路前段.mp3',ogg: ''},
{title: '时间消失之路后段',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间消失之路后段.mp3',ogg: ''},
{title: '时间神殿-TimeTempleInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间神殿-TimeTempleInMirror.mp3',ogg: ''},

{title: '时间裂缝',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间裂缝.mp3',ogg: ''},
{title: '时间隧道',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/时间隧道.mp3',ogg: ''},
{title: '明珠港',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/明珠港.mp3',ogg: ''},
{title: '昔日的荣耀',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/昔日的荣耀.mp3',ogg: ''},
{title: '昭和村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/昭和村.mp3',ogg: ''},
{title: '暗黑龙王',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/暗黑龙王.mp3',ogg: ''},
{title: '未来之门',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/未来之门.mp3',ogg: ''},
{title: '未来之门黄昏勇士部落郊外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/未来之门黄昏勇士部落郊外.mp3',ogg: ''},
{title: '未来射手村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/未来射手村.mp3',ogg: ''},
{title: '未知废矿区',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/未知废矿区.mp3',ogg: ''},
{title: '机库',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/机库.mp3',ogg: ''},

{title: '枫之高校',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/枫之高校.mp3',ogg: ''},
{title: '枫城百间廊下内室',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/枫城百间廊下内室.mp3',ogg: ''},
{title: '格里米尔研究所',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/格里米尔研究所.mp3',ogg: ''},
{title: '桜POP',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/桜POP.mp3',ogg: ''},
{title: '梦幻主题公园',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/梦幻主题公园.mp3',ogg: ''},
{title: '次元图书馆',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/次元图书馆.mp3',ogg: ''},
{title: '武陵-MureungHillInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵-MureungHillInMirror.mp3',ogg: ''},
{title: '武陵-东',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵-东.mp3',ogg: ''},
{title: '武陵',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵.mp3',ogg: ''},
{title: '武陵学院1',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵学院1.mp3',ogg: ''},
{title: '武陵学院2',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵学院2.mp3',ogg: ''},
{title: '武陵学院3',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵学院3.mp3',ogg: ''},
{title: '武陵学院4',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵学院4.mp3',ogg: ''},
{title: '武陵郊外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/武陵郊外.mp3',ogg: ''},
{title: '死亡之林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/死亡之林.mp3',ogg: ''},

{title: '水上市场',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水上市场.mp3',ogg: ''},
{title: '水上市场郊外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水上市场郊外.mp3',ogg: ''},
{title: '水下世界-深海',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水下世界-深海.mp3',ogg: ''},

{title: '水下世界东海',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水下世界东海.mp3',ogg: ''},
{title: '水下世界西海',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水下世界西海.mp3',ogg: ''},
{title: '水晶花园',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水晶花园.mp3',ogg: ''},
{title: '水晶花园航行',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水晶花园航行.mp3',ogg: ''},
{title: '水路迷宫',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/水路迷宫.mp3',ogg: ''},
{title: '江户村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/江户村.mp3',ogg: ''},
{title: '沼泽地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/沼泽地.mp3',ogg: ''},
{title: '泰国地图',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/泰国地图.mp3',ogg: ''},
{title: '海盗船',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/海盗船.mp3',ogg: ''},
{title: '深海峡谷',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/深海峡谷.mp3',ogg: ''},

{title: '火焰之地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/火焰之地.mp3',ogg: ''},
{title: '王者领地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/王者领地.mp3',ogg: ''},
{title: '玛加提亚-DisputeInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玛加提亚-DisputeInMirror.mp3',ogg: ''},

{title: '玩具城-FantasticThinkingInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/玩具城-FantasticThinkingInMirror.mp3',ogg: ''},

{title: '百草堂',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/百草堂.mp3',ogg: ''},
{title: '神之子伤感剧情-NastyLiar',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神之子伤感剧情-NastyLiar.mp3',ogg: ''},
{title: '神之子神殿-BeBornZero',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神之子神殿-BeBornZero.mp3',ogg: ''},
{title: '神之子逗趣剧情-SmileZero',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神之子逗趣剧情-SmileZero.mp3',ogg: ''},
{title: '神兽国际学校大道',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神兽国际学校大道.mp3',ogg: ''},
{title: '神木村-LeafreInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神木村-LeafreInMirror.mp3',ogg: ''},
{title: '神木村-米纳尔森林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神木村-米纳尔森林.mp3',ogg: ''},

{title: '神木村外',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神木村外.mp3',ogg: ''},
{title: '神木村生命的洞窟',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神木村生命的洞窟.mp3',ogg: ''},
{title: '神木村龙林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神木村龙林.mp3',ogg: ''},
{title: '神殿通道',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神殿通道.mp3',ogg: ''},

{title: '神秘的航行',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神秘的航行.mp3',ogg: ''},
{title: '神秘通道',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/神秘通道.mp3',ogg: ''},
{title: '童话村-东部',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/童话村-东部.mp3',ogg: ''},
{title: '童话村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/童话村.mp3',ogg: ''},
{title: '童话村怪物地带',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/童话村怪物地带.mp3',ogg: ''},
{title: '维利塔斯',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/维利塔斯.mp3',ogg: ''},
{title: '群星---Dreaming-Sailor',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/群星---Dreaming-Sailor.mp3',ogg: ''},
{title: '群星---冒险岛11周年经典BGM',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/群星---冒险岛11周年经典BGM.mp3',ogg: ''},
{title: '翼-~memories-of-maple-story~',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/翼-~memories-of-maple-story~.mp3',ogg: ''},
{title: '耀眼繁星',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/耀眼繁星.mp3',ogg: ''},
{title: '艰苦洞穴',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/艰苦洞穴.mp3',ogg: ''},
{title: '艾琳森林-毒雾森林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/艾琳森林-毒雾森林.mp3',ogg: ''},
{title: '艾里葛斯之王座',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/艾里葛斯之王座.mp3',ogg: ''},
{title: '莱班矿山外围',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/莱班矿山外围.mp3',ogg: ''},
{title: '蘑菇城内',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/蘑菇城内.mp3',ogg: ''},
{title: '蘑菇城维京海盗船',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/蘑菇城维京海盗船.mp3',ogg: ''},
{title: '蚂蚁洞',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/蚂蚁洞.mp3',ogg: ''},
{title: '蝙蝠魔船',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/蝙蝠魔船.mp3',ogg: ''},
{title: '被破坏的彩虹岛',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/被破坏的彩虹岛.mp3',ogg: ''},
{title: '被破坏的新叶城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/被破坏的新叶城.mp3',ogg: ''},
{title: '被诅咒的寺院',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/被诅咒的寺院.mp3',ogg: ''},

{title: '诺特勒斯港湾',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/诺特勒斯港湾.mp3',ogg: ''},
{title: '赫里希安外围森林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/赫里希安外围森林.mp3',ogg: ''},
{title: '赫里希安市中心黑市',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/赫里希安市中心黑市.mp3',ogg: ''},
{title: '超能力者创建',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/超能力者创建.mp3',ogg: ''},
{title: '过去的时间神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/过去的时间神殿.mp3',ogg: ''},
{title: '远古的冒险岛',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/远古的冒险岛.mp3',ogg: ''},
{title: '逆奥之城-森林时间门-卡姆那',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/逆奥之城-森林时间门-卡姆那.mp3',ogg: ''},
{title: '逆恩森林',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/逆恩森林.mp3',ogg: ''},
{title: '逐梦飞翔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/逐梦飞翔.mp3',ogg: ''},
{title: '逐梦飞翔伴奏',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/逐梦飞翔伴奏.mp3',ogg: ''},
{title: '通天塔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/通天塔.mp3',ogg: ''},
{title: '通天塔组队任务',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/通天塔组队任务.mp3',ogg: ''},
{title: '通往未来之城',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/通往未来之城.mp3',ogg: ''},
{title: '通往玩具之路',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/通往玩具之路.mp3',ogg: ''},
{title: '遗迹发掘地军营',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/遗迹发掘地军营.mp3',ogg: ''},
{title: '遗迹地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/遗迹地.mp3',ogg: ''},
{title: '里恩-雪地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/里恩-雪地.mp3',ogg: ''},
{title: '里恩岛',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/里恩岛.mp3',ogg: ''},
{title: '镜洞',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/镜洞.mp3',ogg: ''},
{title: '闹鬼宅邸',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/闹鬼宅邸.mp3',ogg: ''},
{title: '阿里安特-AriantInMirror',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/阿里安特-AriantInMirror.mp3',ogg: ''},

{title: '阿里山乐山村',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/阿里山乐山村.mp3',ogg: ''},
{title: '阿里山平原',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/阿里山平原.mp3',ogg: ''},
{title: '霜月はるか---始まりのstory',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/霜月はるか---始まりのstory.mp3',ogg: ''},
{title: '静谧之林极光大神殿',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/静谧之林极光大神殿.mp3',ogg: ''},
{title: '飞龙峡谷',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/飞龙峡谷.mp3',ogg: ''},

{title: '鱼王-boss',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/鱼王-boss.mp3',ogg: ''},
{title: '鲁斯韦尔草原',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/鲁斯韦尔草原.mp3',ogg: ''},
{title: '麦格纳斯',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/麦格纳斯.mp3',ogg: ''},
{title: '黄金海岸',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/黄金海岸.mp3',ogg: ''},
{title: '黑暗圣地',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/黑暗圣地.mp3',ogg: ''},
{title: '黑暗圣地花园',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/黑暗圣地花园.mp3',ogg: ''},
{title: '黑暗的塔',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/黑暗的塔.mp3',ogg: ''},
{title: '黑色之翼',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/黑色之翼.mp3',ogg: ''},
{title: '龙之梦',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/龙之梦.mp3',ogg: ''},
{title: '龙之梦境',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/龙之梦境.mp3',ogg: ''},
{title: '龙的传人',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/龙的传人.mp3',ogg: ''},
{title: '龙神的约定',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/龙神的约定.mp3',ogg: ''},
{title: 'Abandoned-Mine',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Abandoned-Mine.mp3',ogg: ''},
{title: 'Above-The-Treetops',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Above-The-Treetops.mp3',ogg: ''},
{title: 'Acient-Remain',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Acient-Remain.mp3',ogg: ''},
{title: 'Ancient-Move',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Ancient-Move.mp3',ogg: ''},
{title: 'Anthem-For-Heroes',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Anthem-For-Heroes.mp3',ogg: ''},
{title: 'Aqua-Cave',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Aqua-Cave.mp3',ogg: ''},
{title: 'Aquarium',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Aquarium.mp3',ogg: ''},
{title: 'Arab-Pirate',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Arab-Pirate.mp3',ogg: ''},
{title: 'Army-Of-Fears-Theme',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Army-Of-Fears-Theme.mp3',ogg: ''},
{title: 'Bad-Guys',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Bad-Guys.mp3',ogg: ''},
{title: 'BattleOnTheDeck',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/BattleOnTheDeck.mp3',ogg: ''},
{title: 'BigMachine-mission',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/BigMachine-mission.mp3',ogg: ''},
{title: 'BigMachine',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/BigMachine.mp3',ogg: ''},
{title: 'BlackHeavenTheme-parade',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/BlackHeavenTheme-parade.mp3',ogg: ''},
{title: 'BlackHeavenTheme',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/BlackHeavenTheme.mp3',ogg: ''},
{title: 'BlackWing',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/BlackWing.mp3',ogg: ''},
{title: 'Cava-Bien',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Cava-Bien.mp3',ogg: ''},
{title: 'Chinatown',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Chinatown.mp3',ogg: ''},
{title: 'Climbing-Up-The-WorldTree',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Climbing-Up-The-WorldTree.mp3',ogg: ''},
{title: 'Come-With-Me',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Come-With-Me.mp3',ogg: ''},
{title: 'Crimson-Tower',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Crimson-Tower.mp3',ogg: ''},
{title: 'CygnusGarden',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/CygnusGarden.mp3',ogg: ''},
{title: 'DancingWithTheMoon',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/DancingWithTheMoon.mp3',ogg: ''},
{title: 'Decision',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Decision.mp3',ogg: ''},
{title: 'Deep-See',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Deep-See.mp3',ogg: ''},
{title: 'Demian-Spine',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Demian-Spine.mp3',ogg: ''},
{title: 'Demian-True',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Demian-True.mp3',ogg: ''},
{title: 'Demian',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Demian.mp3',ogg: ''},
{title: 'DespairOnDevil',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/DespairOnDevil.mp3',ogg: ''},
{title: 'destructionTown',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/destructionTown.mp3',ogg: ''},
{title: 'Dragon-Dream',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Dragon-Dream.mp3',ogg: ''},
{title: 'DrillHall',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/DrillHall.mp3',ogg: ''},
{title: 'Elfwood',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Elfwood.mp3',ogg: ''},
{title: 'Endless-Journey',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Endless-Journey.mp3',ogg: ''},
{title: 'Eregos',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Eregos.mp3',ogg: ''},
{title: 'Evil-Eyes',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Evil-Eyes.mp3',ogg: ''},
{title: 'Final-Fight',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Final-Fight.mp3',ogg: ''},
{title: 'First-Step-Master',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/First-Step-Master.mp3',ogg: ''},
{title: 'Floral-Life',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Floral-Life.mp3',ogg: ''},
{title: 'Flower-In-Blue',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Flower-In-Blue.mp3',ogg: ''},
{title: 'FlytotheMoon',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/FlytotheMoon.mp3',ogg: ''},
{title: 'GelimerLab',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/GelimerLab.mp3',ogg: ''},
{title: 'GoPicnic',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/GoPicnic.mp3',ogg: ''},
{title: 'Gravity+Core',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Gravity+Core.mp3',ogg: ''},
{title: 'Gravity+Lord+Rise',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Gravity+Lord+Rise.mp3',ogg: ''},
{title: 'Gravity+Lord',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Gravity+Lord.mp3',ogg: ''},
{title: 'HeavenAgain-reprise',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/HeavenAgain-reprise.mp3',ogg: ''},
{title: 'HeavenAgain',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/HeavenAgain.mp3',ogg: ''},
{title: 'HeroComes',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/HeroComes.mp3',ogg: ''},
{title: 'Heroes-Of-Maple-Theme-Piano',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Heroes-Of-Maple-Theme-Piano.mp3',ogg: ''},
{title: 'Heroes-Of-Maple-Theme',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Heroes-Of-Maple-Theme.mp3',ogg: ''},
{title: 'HighlandStar',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/HighlandStar.mp3',ogg: ''},
{title: 'Jazz-For-Dr-Lim',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Jazz-For-Dr-Lim.mp3',ogg: ''},
{title: 'Jungle-Book',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Jungle-Book.mp3',ogg: ''},
{title: 'JunkYard',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/JunkYard.mp3',ogg: ''},
{title: 'Kerning-Square-Field',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Kerning-Square-Field.mp3',ogg: ''},
{title: 'Kerning-Square-Subway',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Kerning-Square-Subway.mp3',ogg: ''},
{title: 'Kerning-Square',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Kerning-Square.mp3',ogg: ''},
{title: 'knightsStronghold',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/knightsStronghold.mp3',ogg: ''},
{title: 'Krease-Agit',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Krease-Agit.mp3',ogg: ''},
{title: 'Krease-Colosseum',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Krease-Colosseum.mp3',ogg: ''},
{title: 'Krease-Field',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Krease-Field.mp3',ogg: ''},
{title: 'Lion-Castle',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Lion-Castle.mp3',ogg: ''},
{title: 'Lion-Heart',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Lion-Heart.mp3',ogg: ''},
{title: 'LIST.TXT',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/LIST.TXT.mp3',ogg: ''},
{title: 'Lost-In-A-Dream',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Lost-In-A-Dream.mp3',ogg: ''},
{title: 'Mine-Quest',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Mine-Quest.mp3',ogg: ''},
{title: 'Missing-You',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Missing-You.mp3',ogg: ''},
{title: 'Moonlight-Shadow',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Moonlight-Shadow.mp3',ogg: ''},
{title: 'Mush-Catle',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Mush-Catle.mp3',ogg: ''},
{title: 'New-White-Christmas',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/New-White-Christmas.mp3',ogg: ''},
{title: 'Nightmare',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Nightmare.mp3',ogg: ''},
{title: 'NxLogo',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/NxLogo.mp3',ogg: ''},
{title: 'Pain-And-Sorrow',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Pain-And-Sorrow.mp3',ogg: ''},
{title: 'Pain-To-Hope',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Pain-To-Hope.mp3',ogg: ''},
{title: 'Play-With-Me',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Play-With-Me.mp3',ogg: ''},
{title: 'Plot-Of-Pixie',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Plot-Of-Pixie.mp3',ogg: ''},
{title: 'PromiseOfHeaven-vocaless',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PromiseOfHeaven-vocaless.mp3',ogg: ''},
{title: 'PromiseOfHeaven',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PromiseOfHeaven.mp3',ogg: ''},
{title: 'PVP准备地图',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PVP准备地图.mp3',ogg: ''},
{title: 'PVP场景背景音乐A',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PVP场景背景音乐A.mp3',ogg: ''},
{title: 'PVP场景背景音乐B',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PVP场景背景音乐B.mp3',ogg: ''},
{title: 'PVP场景背景音乐C',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PVP场景背景音乐C.mp3',ogg: ''},
{title: 'PVP场景背景音乐D',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/PVP场景背景音乐D.mp3',ogg: ''},
{title: 'QueensGarden',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/QueensGarden.mp3',ogg: ''},
{title: 'RabbitsDream',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/RabbitsDream.mp3',ogg: ''},
{title: 'Rest·N·Peace',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Rest·N·Peace.mp3',ogg: ''},
{title: 'RoyalGuard',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/RoyalGuard.mp3',ogg: ''},
{title: 'RuinCastle',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/RuinCastle.mp3',ogg: ''},
{title: 'Secret-Flower',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Secret-Flower.mp3',ogg: ''},
{title: 'SecretMission',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/SecretMission.mp3',ogg: ''},
{title: 'SecretMissionBase',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/SecretMissionBase.mp3',ogg: ''},
{title: 'ShininHarbor',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/ShininHarbor.mp3',ogg: ''},
{title: 'Shining-Sea',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Shining-Sea.mp3',ogg: ''},
{title: 'Showtime',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Showtime.mp3',ogg: ''},
{title: 'Smile-Love-You-(short-ver)(伴奏)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Smile-Love-You-(short-ver)(伴奏).mp3',ogg: ''},
{title: 'Smile-Love-You-(short-ver)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Smile-Love-You-(short-ver).mp3',ogg: ''},
{title: 'Smile-Love-You(伴奏)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Smile-Love-You(伴奏).mp3',ogg: ''},
{title: 'Smile-Love-You(日文版)',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Smile-Love-You(日文版).mp3',ogg: ''},
{title: 'Smile-Love-You',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Smile-Love-You.mp3',ogg: ''},
{title: 'Sound-Of-Elf',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/Sound-Of-Elf.mp3',ogg: ''},
{title: 'SpeakInTheVoid',
artist: 'Wizet',
album: 'MapleStory',
cover:'img/1.jpg',
mp3: 'mp3/SpeakInTheVoid.mp3',ogg: ''},
];

	// Load playlist
	for (var i=0; i<playlist.length; i++){
		var item = playlist[i];
		$('#playlist').append('<li>'+item.artist+' - '+item.title+'</li>');
	}

	var time = new Date(),
		currentTrack = shuffle === 'true' ? time.getTime() % playlist.length : 0,
		trigger = false,
		audio, timeout, isPlaying, playCounts;

	var play = function(){
		audio.play();
		$('.playback').addClass('playing');
		timeout = setInterval(updateProgress, 500);
		isPlaying = true;
	}

	var pause = function(){
		audio.pause();
		$('.playback').removeClass('playing');
		clearInterval(updateProgress);
		isPlaying = false;
	}

	// Update progress
	var setProgress = function(value){
		var currentSec = parseInt(value%60) < 10 ? '0' + parseInt(value%60) : parseInt(value%60),
			ratio = value / audio.duration * 100;

		$('.timer').html(parseInt(value/60)+':'+currentSec);
		$('.progress .pace').css('width', ratio + '%');
		$('.progress .slider a').css('left', ratio + '%');
	}

	var updateProgress = function(){
		setProgress(audio.currentTime);
	}

	// Progress slider
	$('.progress .slider').slider({step: 0.1, slide: function(event, ui){
		$(this).addClass('enable');
		setProgress(audio.duration * ui.value / 100);
		clearInterval(timeout);
	}, stop: function(event, ui){
		audio.currentTime = audio.duration * ui.value / 100;
		$(this).removeClass('enable');
		timeout = setInterval(updateProgress, 500);
	}});

	// Volume slider
	var setVolume = function(value){
		audio.volume = localStorage.volume = value;
		$('.volume .pace').css('width', value * 100 + '%');
		$('.volume .slider a').css('left', value * 100 + '%');
	}

	var volume = localStorage.volume || 0.5;
	$('.volume .slider').slider({max: 1, min: 0, step: 0.01, value: volume, slide: function(event, ui){
		setVolume(ui.value);
		$(this).addClass('enable');
		$('.mute').removeClass('enable');
	}, stop: function(){
		$(this).removeClass('enable');
	}}).children('.pace').css('width', volume * 100 + '%');

	$('.mute').click(function(){
		if ($(this).hasClass('enable')){
			setVolume($(this).data('volume'));
			$(this).removeClass('enable');
		} else {
			$(this).data('volume', audio.volume).addClass('enable');
			setVolume(0);
		}
	});

	// Switch track
	var switchTrack = function(i){
		if (i < 0){
			track = currentTrack = playlist.length - 1;
		} else if (i >= playlist.length){
			track = currentTrack = 0;
		} else {
			track = i;
		}

		$('audio').remove();
		loadMusic(track);
		if (isPlaying == true) play();
	}

	// Shuffle
	var shufflePlay = function(){
		var time = new Date(),
			lastTrack = currentTrack;
		currentTrack = time.getTime() % playlist.length;
		if (lastTrack == currentTrack) ++currentTrack;
		switchTrack(currentTrack);
	}

	// Fire when track ended
	var ended = function(){
		pause();
		audio.currentTime = 0;
		playCounts++;
		if (continous == true) isPlaying = true;
		if (repeat == 1){
			play();
		} else {
			if (shuffle === 'true'){
				shufflePlay();
			} else {
				if (repeat == 2){
					switchTrack(++currentTrack);
				} else {
					if (currentTrack < playlist.length) switchTrack(++currentTrack);
				}
			}
		}
	}

	var beforeLoad = function(){
		var endVal = this.seekable && this.seekable.length ? this.seekable.end(0) : 0;
		$('.progress .loaded').css('width', (100 / (this.duration || 1) * endVal) +'%');
	}

	// Fire when track loaded completely
	var afterLoad = function(){
		if (autoplay == true) play();
	}

	// Load track
	var loadMusic = function(i){
		var item = playlist[i],
			newaudio = $('<audio>').html('<source src="'+item.mp3+'"><source src="'+item.ogg+'">').appendTo('#player');
		
		$('.cover').html('<img src="'+item.cover+'" alt="'+item.album+'">');
		$('.tag').html('<strong>'+item.title+'</strong><span class="artist">'+item.artist+'</span><span class="album">'+item.album+'</span>');
		$('#playlist li').removeClass('playing').eq(i).addClass('playing');
		audio = newaudio[0];
		audio.volume = $('.mute').hasClass('enable') ? 0 : volume;
		audio.addEventListener('progress', beforeLoad, false);
		audio.addEventListener('durationchange', beforeLoad, false);
		audio.addEventListener('canplay', afterLoad, false);
		audio.addEventListener('ended', ended, false);
	}

	loadMusic(currentTrack);
	$('.playback').on('click', function(){
		if ($(this).hasClass('playing')){
			pause();
		} else {
			play();
		}
	});
	$('.rewind').on('click', function(){
		if (shuffle === 'true'){
			shufflePlay();
		} else {
			switchTrack(--currentTrack);
		}
	});
	$('.fastforward').on('click', function(){
		if (shuffle === 'true'){
			shufflePlay();
		} else {
			switchTrack(++currentTrack);
		}
	});
	$('#playlist li').each(function(i){
		var _i = i;
		$(this).on('click', function(){
			switchTrack(_i);
		});
	});

	if (shuffle === 'true') $('.shuffle').addClass('enable');
	if (repeat == 1){
		$('.repeat').addClass('once');
	} else if (repeat == 2){
		$('.repeat').addClass('all');
	}

	$('.repeat').on('click', function(){
		if ($(this).hasClass('once')){
			repeat = localStorage.repeat = 2;
			$(this).removeClass('once').addClass('all');
		} else if ($(this).hasClass('all')){
			repeat = localStorage.repeat = 0;
			$(this).removeClass('all');
		} else {
			repeat = localStorage.repeat = 1;
			$(this).addClass('once');
		}
	});

	$('.shuffle').on('click', function(){
		if ($(this).hasClass('enable')){
			shuffle = localStorage.shuffle = 'false';
			$(this).removeClass('enable');
		} else {
			shuffle = localStorage.shuffle = 'true';
			$(this).addClass('enable');
		}
	});
})(jQuery);